#pragma once

#include <vector>

#include <RiderModeChoice/UtilityLogit/utility.h>
#include <RiderModeChoice/UtilityLogit/types.h>
#include "RiderModeChoice/UtilityLogit/csvUtils.h"
#include <RiderModeChoice/TransportMode.h>
#include <KARRI/Algorithms/KaRRi/RequestState/RequestState.h>
#include "KARRI/Algorithms/KaRRi/Stats/PerformanceStats.h"
#include "PTLeg/PTResult.h"

constexpr char parametersFileContent[] =
#include <RiderModeChoice/UtilityLogit/autogenerated_includable_parameters>
    ;

namespace karri {
    using namespace mode_choice;
    using namespace mode_choice::utility_logit;

    // Computes a PT journey with walking but without taxi legs.
    template<
        typename PTQueryT,
        typename PTAlgorithmT
    >
    class PTJourneyFinder {
    public:
        PTJourneyFinder(const std::vector<PTQueryT> &queries,
                        PTAlgorithmT &ptAlgorithm)
            : queries(queries),
              ptAlgorithm(ptAlgorithm),
              params(loadParametersFromCSV<TransportMode, ModeParameters>(std::stringstream(parametersFileContent),
                                                                          stringToTransportMode,
                                                                          fromMap)[TransportMode::PublicTransport]) {
        }

        PTResult findBestJourney(const RequestState &requestState,
                                 stats::PtPerformanceStats &stats) {
            const auto query = queries[requestState.originalRequest.requestId];
            const int originPsgEdge = query.originPsgEdge;
            const int originVehEdge = query.originVehEdge;
            const int destPsgEdge = query.destinationPsgEdge;
            const int destVehEdge = query.destinationVehEdge;

            ptAlgorithm.run(originPsgEdge, originVehEdge, destPsgEdge, destVehEdge, query.departureTime, stats);
            latestJourneys = ptAlgorithm.getJourneys();
            const auto journey = pickJourneyWithBestUtility(latestJourneys, requestState.originalRequest);
            if (journey.empty() || (journey.size() == 1 && !journey[0].usesRoute)) {
                // No valid PT journey found, return empty result
                return {{}, INFTY};
            }
            KASSERT(RAPTOR::countTrips(journey) > 0, "Best journey found by PT algorithm does not use any routes, invalid result!");
            int numTransfers = RAPTOR::countTrips(journey) - 1;
            const int cost = CostCalculator::calcPTJourneyCost(
                parrot::ultraToKarriTime(journey.back().arrivalTime) - requestState.originalRequest.requestTime,
                parrot::ultraToKarriTime(RAPTOR::totalTransferTime(journey)),
                numTransfers);

            PTResult ptOnlyResponse(journey, cost);

            return ptOnlyResponse;
        }

        int getBestCostOfAnyJourneyFromLastRun(const int reqTime) const {
            int bestCost = INFTY;
            for (const auto &journey: latestJourneys) {
                if (journey.empty()) continue;
                int numTransfers = RAPTOR::countTrips(journey);
                if (numTransfers > 0) --numTransfers; // number of transfers is number of trips - 1 but at least 0
                const int cost = CostCalculator::calcPTJourneyCost(
                    parrot::ultraToKarriTime(journey.back().arrivalTime) - reqTime,
                    parrot::ultraToKarriTime(RAPTOR::totalTransferTime(journey)),
                    numTransfers);
                if (cost < bestCost) {
                    bestCost = cost;
                }
            }
            return bestCost;
        }

    private:
        RAPTOR::Journey pickJourneyWithBestUtility(const std::vector<RAPTOR::Journey> &journeys,
                                                   const Request &request) const {
            double bestUtility = -std::numeric_limits<double>::infinity();
            int bestJourneyIdx = -1;

            for (int i = 0; i < journeys.size(); ++i) {
                const auto &journey = journeys[i];
                if (journey.empty()) continue;
                const int journeyTime = parrot::ultraToKarriTime(journey.back().arrivalTime) - request.requestTime;
                const int totalTransferTime = parrot::ultraToKarriTime(RAPTOR::totalTransferTime(journey));
                const int inVehicleTime = parrot::ultraToKarriTime(getTotalInVehicleTime(journey));
                const int waitTime = journeyTime - inVehicleTime - totalTransferTime;
                KASSERT(inVehicleTime >= 0 && waitTime >= 0 && totalTransferTime >= 0, "Negative time component in journey! Journey time = " << journeyTime <<
                    ", in-vehicle time = " << inVehicleTime << ", wait time = " << waitTime << ", transfer time = " << totalTransferTime);
                const Attributes attributes = constructAttributesForTimesInTenthsOfSeconds(
                    inVehicleTime, waitTime, totalTransferTime);
                const double utility = exampleUtilityFunction(attributes, params);
                if (utility > bestUtility) {
                    bestUtility = utility;
                    bestJourneyIdx = i;
                }
            }
            if (bestJourneyIdx == -1) {
                return {};
            }
            KASSERT(bestJourneyIdx >= 0 && bestJourneyIdx < journeys.size(), "Best journey index is out of bounds!");
            return journeys[bestJourneyIdx];
        }

        static int getTotalInVehicleTime(const RAPTOR::Journey &journey) {
            int totalSeconds = 0;
            for (const auto &leg: journey) {
                if (leg.usesRoute) {
                    totalSeconds += leg.arrivalTime - leg.departureTime;
                }
            }
            return totalSeconds;
        }

        const std::vector<PTQueryT> &queries;
        PTAlgorithmT &ptAlgorithm;
        const ModeParameters params; // Utility function parameters for mode choice, used to pick best journey

        std::vector<RAPTOR::Journey> latestJourneys;
    };
}
